# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ANPR
email: 
description: >- 
  ANPR
author: Team Digitale e AgID
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 
main_institution: 
  name: Ministero dell'Interno
  url: http://www.interno.gov.it/it
main_brand: ANPR
main_brand__payoff: Anagrafe Nazionale Popolazione Residente
main_socials:
  string: 'Segui ANPR su:'
  socials:
    - name: github
      url: https://github.com/italia/anpr
      icon: '/assets/images/icons/ico-github.svg'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap

exclude:
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  - yarn.lock

sass:
    load_paths:
      - _sass
      - node_modules
    sass_dir: /